- name: Test create directory and file
  hosts: all
  become: true
  tasks:
    - name: Create a test directory
      ansible.builtin.file:
        path: /tmp/test_ansible_dir
        state: directory
        mode: '0755'

    - name: Create a test file
      ansible.builtin.copy:
        content: "This is a test file created by Ansible.\n"
        dest: /tmp/test_ansible_dir/testfile.txt
        mode: '0644'
