- name: Install Docker on Debian/Ubuntu
  hosts: vboxuser_server  # <- this must match a group/host in your inventory
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
